### ISSUE TITLE
Wrong key?

### ISSUE THREAD

**Issue by DTEX123** [somethingcoolmustbehere/dumpPakKey#2]
I tried two projects but not worked with umodel.
One is my project and the real key is pUJc39WdcbUfAcaE5tEgtPWdaXDVXl7XGtrhmpzet4M=
I got 9H9f6HFpm6jUTrJkrk6pBoupAZ6aBFRdR5BHlHswhxY=
Using both python complied bulid and release

{
    "$type": "1",
    "$types": {
        "UnrealBuildTool.EncryptionAndSigning+CryptoSettings, UnrealBuildTool, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null": "1",
        "UnrealBuildTool.EncryptionAndSigning+EncryptionKey, UnrealBuildTool, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null": "2",
        "UnrealBuildTool.EncryptionAndSigning+SigningKey, UnrealBuildTool, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null": "4",
        "UnrealBuildTool.EncryptionAndSigning+SigningKeyPair, UnrealBuildTool, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null": "3"
    },
    "EncryptionKey": {
        "$type": "2",
        "Guid": "null",
        "Key": "9H9f6HFpm6jUTrJkrk6pBoupAZ6aBFRdR5BHlHswhxY=",
        "Name": "null"
    },
    "PakEncryptionRequired": "true",
    "PakSigningRequired": "true",
    "SecondaryEncryptionKeys": "[ ]",
    "SigningKey": "null",
    "bDataCryptoRequired": "true",
    "bEnablePakFullAssetEncryption": "false",
    "bEnablePakIndexEncryption": "true",
    "bEnablePakIniEncryption": "true",
    "bEnablePakSigning": "true",
    "bEnablePakUAssetEncryption": "true"
}

**Comment by somethingcoolmustbehere** [comment]
updated. ## added ctrl+v functionality for ueviewer and other 3rd party apps (hex representation of a key copied to your clipboard)
mb messed up with keys, it clearly searches key block with defined pattern, that pattern doesn't changing, so the problem is on your side. I get same results (keys are identical on dumpakkey output and in project file(crypto section) )

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
